import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body data-theme="autumn" className="bg-cover bg-no-repeat" style={{ backgroundImage: `url(${bg.src})` }}> */}
      <body data-theme="autumn">
        <h1>Root Layout</h1>
        {children}
      </body>
    </html>
  )
}
